# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

destination: _site
sass:
  sass_dir: _sass
  style: expanded # compressed # expanded

# default language, permalink and highlighter
lang        : en
date_format : "%b %-d, %Y"
permalink   : /:title
markdown    : kramdown
highlighter : pygments

# SEO settings
title: "yookoala"
description: "Web 技工雜記"
keywords: "Jekyll, theme, free, download, SEO, blog, web"

# Site settings
url: https://yookoala.github.io
#baseurl: "/dotX"
baseurl: ""

# Navigation
nav:
  -
    title   : 中文
    url     : /zh-hk/
  -
    title   : English
    url     : /en/

# Repositories to advertise on this site
repos:
  -
    title   : gitsocket
    url     : https://yookoala.github.io/gitsocket/

# Author settings
author:
  name      : 樹雄
  job       : Web Developer
  bio       : "golang, nodjs, php"
  thumb     : /assets/images/avatar.jpg
  email     : koalay@gmail.com
  github    : https://github.com/yookoala
  linkedin  : https://www.linkedin.com/in/koalayeung
  #url       : https://yookoala.github.io
  #twitter   :

# google_analytics: UA-52446115-1
repo: http://github.com/yookoala/yookoala.github.io

# comments
#disqus_shortname: "fernandomoreira"


# for multilangual
# ref: https://www.sylvaindurand.org/making-jekyll-multilingual/
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: post
      lang: en
      date_format : "%b %-d, %Y"
      permalink   : /en/:title/:year:month:day/
  -
    scope:
      path: _posts/zh-hk
    values:
      layout: post
      lang: zh-hk
      date_format: "%Y 年 %m 月 %d 日"
      permalink   : /zh-hk/:title/:year:month:day/

exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'travisGemfile']
